# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: neuvectorLicense
  displayName: Get NV license
  inputs:
    secureFile: 'neuvector-license.txt'
- task: NeuVectorScan@1
  inputs:
    scanType: 'standalone'
    license: '$(neuvectorLicense.secureFilePath)'
    nvContainerRegistry: 'docker_lsong'
    nvRepository: 'test/scanner'
    nvTag: 'latest'
    containerRegistry: 'docker_lsong'
    repository: 'library/alpine'
    tag: '3.6'
    scanLayers: true
