# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - main

services:
  neuvector: neuvector

steps:
      - task: DownloadSecureFile@1
        name: nvLicense
        displayName: NV License
        inputs:
         secureFile: 'nv_license.txt'
      - task: NeuVectorScan@1
        inputs:
            controllerType: 'local'
            controllerLicense: '$(nvLicense.secureFilePath)'
            containerRegistry: 'docker_hub_lsong'
            repository: 'songlongtj/alpine'
            tag: '3.6'
            failOnHighSeverityThreshold: true
            highSeverityThreshold: '3'
            failOnMediumSeverityThreshold: true
            mediumSeverityThreshold: '3'

resources:
  containers:
  - container: neuvector
    image: neuvector/controller:3.0.0.b3
    endpoint: 'docker_hub_lsong'
    ports:
      - 18300:18300
      - 18301:18301
      - 18400:18400
      - 18401:18401
      - 10443:10443
    volumes:
      - /lib/modules:/lib/modules
      - /var/neuvector:/var/neuvector
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/host/cgroup
      - /proc:/host/proc
    options: --pid=host --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --cap-add=SYS_PTRACE --cap-add=IPC_LOCK --security-opt apparmor:unconfined --env CLUSTER_JOIN_ADDR=neuvector --env CTRL_SERVER_PORT=10443
# resources:
# - repo: self

# variables:
#   - name: tag
#     value: $(Build.BuildId)
#   - name: license
#     value: qV9GKO13z+RjlhmAbpoOd1LPzxsi9+4m9iY0HtmB6Wnk0VtQA2bCSQVjm/9uKv2WfbbIYGXg9KQDb8K/Yk71eE+Au6dPdoheipuvv+pgZIxgI/VJKTPqoE/nHyh3ZF2aRct+63TmgNc5GGdSWayzgR69k7Nus1ufQBwxVsmHBJw9LQHyVLzh6pHKRNLeRUy+VzGsO25N6dYSpiz11RiadtQOV8O10a8FXRMFJq5cAy/OPM0xmT1y3KvymITCVFIIac2g/qn9KDOnTHJkOs4yAEVC1NLvdZfJu+gTJ+m5q0TDWvhIE5RwjeeR7pmuUD12+UW4AfCGMUTUpJ49GVssUZBkAG9jMM55/uR3A/YHS3mDiTlRdJhZ+shumT2YOmdt0YuDt+R7NqpH5bukJwGqpgxfo5Atc1eupQFukCfZAcf5MBM8q0wLqDorgDX3AbTizxYDbvccbDcohp2cRCOx+cPOeOqnzpNvp2ZjsDZeDhTqXLNF+Y/dGk3CJ7EiSdX//s3ZXfVthWqlxPYarY3YwKLU/0guWoMT97KTc6+Sp6iZWz2iwLvYG/vo1uJhVtr4eJvVfzGSQVFFJxNgltgAx4CYISPayTZHZxjsJ7PG4qf80L6AL/heNRtmO72hLIB4/AjnkIUB0pifcWfWwG55xP7hmliFKreFKBPi+zW9PNhDFRYdLRxEzXANJLtNbLwZGVlfoykHO0c+0AfYIQWjnsPanpQtT1CLiU0MkYouJIdXzlXxPqucsKzIsgfeFJy3RB+Tr2Y5YA7aLE6wjWqMh2NWnoQSZxbBoVN5kYbhrGqUExq2XUJVYujsP4YSugSLSYk6kkuWDcOaOnCWDxFypAR7aqWnKAnWW6eM6YcLwY9+5Bhbu88i8orW7OZyq9bPpT/NqLt4yruHPiB1PO5g9b4sjlUhzhUrfHl/gL4ySrE1ghVBj6cufJc5DaLaM6yp6sR5Y3ax64O9EtaX57F4KYupLHQ=

# stages:
# - stage: Build
#   displayName: Build image
#   jobs:  
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
      # - task: Docker@21
      #   displayName: Build an image
      #   inputs:
      #     command: build
      #     dockerfile: '**/Dockerfile'
      #     tags: |
      #       $(tag)
      # - script: |
      #     echo " $(Build.BuildId) hello world { $(tag) }"
      #     docker login -u songlongtj -p neuvector
      #     docker pull library/alpine:latest
      #     docker tag alpine:latest lsong/lsong:1.0
      #   displayName: show build number and current path
      # - powershell: |
      #     Get-ChildItem -Path Env:
      #   displayName: print Env info
      # - script: |
      #     docker image ls
      #     docker run --name neuvector.scanner --rm -e SCANNER_REPOSITORY=lsong/lsong -e SCANNER_TAG=1.0 -e SCANNER_LICENSE=$(license) -v /var/run/docker.sock:/var/run/docker.sock -v /var/neuvector:/var/neuvector  neuvector/scanner
      #     cat /var/neuvector/scan_result.json
      #   displayName: show docker
      # - task: NeuVectorScan@1
      #   displayName: Scan Image with NeuVector-lsong
      #   inputs:
      #     controllerType: 'external'
      #     neuvectorController: 'nv_external_controller'
      #     containerRegistry: 'docker_hub_lsong'
      #     repository: 'songlongtj/alpine'
      #     tag: '3.6'
      #     failOnHighSeverityThreshold: true
      #     highSeverityThreshold: '3'
      #     failOnMediumSeverityThreshold: true
      #     mediumSeverityThreshold: '3'
