# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  - name: tag
    value: $(Build.BuildId)

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          echo " $(Build.BuildId) hello world { $(tag) }"
          pwd
        displayName: show build number and current path
      - powershell: |
          Get-ChildItem -Path Env:
        displayName: print Env info
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '**/Dockerfile'
    #     tags: |
    #       $(tag)
    # - task: NeuVectorScan@1
    #   displayName: Scan Image with NeuVector-lsong
    #   inputs:
    #     controllerType: 'external'
    #     neuvectorController: 'NV controller on 89'
    #     containerRegistry: 'lsong docker registry'
    #     repository: 'songlongtj/alpine'
    #     tag: '3.6'
    #     failOnHighSeverityThreshold: true
    #     highSeverityThreshold: '10'
    #     failOnMediumSeverityThreshold: true
    #     mediumSeverityThreshold: '10'